/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeploymentFailure = IDL.Record({
  'message' : IDL.Text,
  'details' : IDL.Opt(IDL.Text),
});
export const DeploymentStatus = IDL.Variant({
  'failure' : DeploymentFailure,
  'success' : IDL.Text,
});
export const VersionInfo = IDL.Record({
  'status' : DeploymentStatus,
  'version' : IDL.Text,
});
export const PrePublishConfig = IDL.Record({
  'missingArtifacts' : IDL.Bool,
  'misconfiguredCanister' : IDL.Bool,
  'frontendBuildFailed' : IDL.Bool,
});
export const PrePublishFailure = IDL.Record({
  'details' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const PrePublishResult = IDL.Variant({
  'failed' : PrePublishFailure,
  'passed' : IDL.Null,
});

export const idlService = IDL.Service({
  'getAllVersions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, VersionInfo))],
      ['query'],
    ),
  'getCurrentVersion' : IDL.Func([], [IDL.Opt(VersionInfo)], ['query']),
  'getVersion' : IDL.Func([IDL.Text], [IDL.Opt(VersionInfo)], ['query']),
  'prePublishCheck' : IDL.Func([PrePublishConfig], [PrePublishResult], []),
  'recordDeployment' : IDL.Func([IDL.Text, DeploymentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeploymentFailure = IDL.Record({
    'message' : IDL.Text,
    'details' : IDL.Opt(IDL.Text),
  });
  const DeploymentStatus = IDL.Variant({
    'failure' : DeploymentFailure,
    'success' : IDL.Text,
  });
  const VersionInfo = IDL.Record({
    'status' : DeploymentStatus,
    'version' : IDL.Text,
  });
  const PrePublishConfig = IDL.Record({
    'missingArtifacts' : IDL.Bool,
    'misconfiguredCanister' : IDL.Bool,
    'frontendBuildFailed' : IDL.Bool,
  });
  const PrePublishFailure = IDL.Record({
    'details' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const PrePublishResult = IDL.Variant({
    'failed' : PrePublishFailure,
    'passed' : IDL.Null,
  });
  
  return IDL.Service({
    'getAllVersions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, VersionInfo))],
        ['query'],
      ),
    'getCurrentVersion' : IDL.Func([], [IDL.Opt(VersionInfo)], ['query']),
    'getVersion' : IDL.Func([IDL.Text], [IDL.Opt(VersionInfo)], ['query']),
    'prePublishCheck' : IDL.Func([PrePublishConfig], [PrePublishResult], []),
    'recordDeployment' : IDL.Func([IDL.Text, DeploymentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };