/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeploymentFailure {
  'message' : string,
  'details' : [] | [string],
}
export type DeploymentStatus = { 'failure' : DeploymentFailure } |
  { 'success' : string };
export interface PrePublishConfig {
  'missingArtifacts' : boolean,
  'misconfiguredCanister' : boolean,
  'frontendBuildFailed' : boolean,
}
export interface PrePublishFailure {
  'details' : [] | [string],
  'reason' : string,
}
export type PrePublishResult = { 'failed' : PrePublishFailure } |
  { 'passed' : null };
export interface VersionInfo { 'status' : DeploymentStatus, 'version' : string }
export interface _SERVICE {
  'getAllVersions' : ActorMethod<[], Array<[string, VersionInfo]>>,
  'getCurrentVersion' : ActorMethod<[], [] | [VersionInfo]>,
  'getVersion' : ActorMethod<[string], [] | [VersionInfo]>,
  'prePublishCheck' : ActorMethod<[PrePublishConfig], PrePublishResult>,
  'recordDeployment' : ActorMethod<[string, DeploymentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];