/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VersionInfo {
    status: DeploymentStatus;
    version: string;
}
export type DeploymentStatus = {
    __kind__: "failure";
    failure: DeploymentFailure;
} | {
    __kind__: "success";
    success: string;
};
export type PrePublishResult = {
    __kind__: "failed";
    failed: PrePublishFailure;
} | {
    __kind__: "passed";
    passed: null;
};
export interface DeploymentFailure {
    message: string;
    details?: string;
}
export interface PrePublishConfig {
    missingArtifacts: boolean;
    misconfiguredCanister: boolean;
    frontendBuildFailed: boolean;
}
export interface PrePublishFailure {
    details?: string;
    reason: string;
}
export interface backendInterface {
    getAllVersions(): Promise<Array<[string, VersionInfo]>>;
    getCurrentVersion(): Promise<VersionInfo | null>;
    getVersion(version: string): Promise<VersionInfo | null>;
    prePublishCheck(config: PrePublishConfig): Promise<PrePublishResult>;
    recordDeployment(version: string, status: DeploymentStatus): Promise<void>;
}
import type { DeploymentFailure as _DeploymentFailure, DeploymentStatus as _DeploymentStatus, PrePublishFailure as _PrePublishFailure, PrePublishResult as _PrePublishResult, VersionInfo as _VersionInfo } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllVersions(): Promise<Array<[string, VersionInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVersions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVersions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentVersion(): Promise<VersionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentVersion();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentVersion();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVersion(arg0: string): Promise<VersionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVersion(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVersion(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async prePublishCheck(arg0: PrePublishConfig): Promise<PrePublishResult> {
        if (this.processError) {
            try {
                const result = await this.actor.prePublishCheck(arg0);
                return from_candid_PrePublishResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.prePublishCheck(arg0);
            return from_candid_PrePublishResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordDeployment(arg0: string, arg1: DeploymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDeployment(arg0, to_candid_DeploymentStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDeployment(arg0, to_candid_DeploymentStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DeploymentFailure_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeploymentFailure): DeploymentFailure {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DeploymentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeploymentStatus): DeploymentStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PrePublishFailure_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrePublishFailure): PrePublishFailure {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PrePublishResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrePublishResult): PrePublishResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_VersionInfo_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VersionInfo): VersionInfo {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VersionInfo]): VersionInfo | null {
    return value.length === 0 ? null : from_candid_VersionInfo_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    details: [] | [string];
    reason: string;
}): {
    details?: string;
    reason: string;
} {
    return {
        details: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.details)),
        reason: value.reason
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DeploymentStatus;
    version: string;
}): {
    status: DeploymentStatus;
    version: string;
} {
    return {
        status: from_candid_DeploymentStatus_n5(_uploadFile, _downloadFile, value.status),
        version: value.version
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    details: [] | [string];
}): {
    message: string;
    details?: string;
} {
    return {
        message: value.message,
        details: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.details))
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _VersionInfo]): [string, VersionInfo] {
    return [
        value[0],
        from_candid_VersionInfo_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failed: _PrePublishFailure;
} | {
    passed: null;
}): {
    __kind__: "failed";
    failed: PrePublishFailure;
} | {
    __kind__: "passed";
    passed: null;
} {
    return "failed" in value ? {
        __kind__: "failed",
        failed: from_candid_PrePublishFailure_n13(_uploadFile, _downloadFile, value.failed)
    } : "passed" in value ? {
        __kind__: "passed",
        passed: value.passed
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failure: _DeploymentFailure;
} | {
    success: string;
}): {
    __kind__: "failure";
    failure: DeploymentFailure;
} | {
    __kind__: "success";
    success: string;
} {
    return "failure" in value ? {
        __kind__: "failure",
        failure: from_candid_DeploymentFailure_n7(_uploadFile, _downloadFile, value.failure)
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _VersionInfo]>): Array<[string, VersionInfo]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function to_candid_DeploymentFailure_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeploymentFailure): _DeploymentFailure {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_DeploymentStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeploymentStatus): _DeploymentStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    details?: string;
}): {
    message: string;
    details: [] | [string];
} {
    return {
        message: value.message,
        details: value.details ? candid_some(value.details) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "failure";
    failure: DeploymentFailure;
} | {
    __kind__: "success";
    success: string;
}): {
    failure: _DeploymentFailure;
} | {
    success: string;
} {
    return value.__kind__ === "failure" ? {
        failure: to_candid_DeploymentFailure_n17(_uploadFile, _downloadFile, value.failure)
    } : value.__kind__ === "success" ? {
        success: value.success
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
